### ISSUE TITLE
Can't recreate smclarify example on AWS SageMaker. Bias report gives: CDDL metrics failed

### ISSUE THREAD

**Issue by Oliver-Chalkley** [aws/amazon-sagemaker-clarify#106]
When I try to run Bias_metrics_usage.ipynb from the examples in https://github.com/aws/amazon-sagemaker-clarify.git in a SageMaker studio notebook I get the following error from the following line (there was originally a Numpy error that I fixed by upgrading Pandas - other than that no other errors):

```
report.bias_report(df, facet_column, label_column, stage_type=report.StageType.PRE_TRAINING)

CDDL metrics failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/report.py", line 292, in _categorical_metric_call_wrapper
    group_variable=group_variable,
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/__init__.py", line 26, in call_metric
    return metric(**{key: kwargs[key] for key in inspect.signature(metric).parameters.keys()})
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/pretraining.py", line 195, in CDDL
    return common.CDD(feature, sensitive_facet_index, positive_label_index, group_variable)
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/common.py", line 80, in CDD
    raise ValueError("Group variable is empty or not provided")
ValueError: Group variable is empty or not provided
CDDL metrics failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/report.py", line 292, in _categorical_metric_call_wrapper
    group_variable=group_variable,
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/__init__.py", line 26, in call_metric
    return metric(**{key: kwargs[key] for key in inspect.signature(metric).parameters.keys()})
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/pretraining.py", line 195, in CDDL
    return common.CDD(feature, sensitive_facet_index, positive_label_index, group_variable)
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/common.py", line 80, in CDD
    raise ValueError("Group variable is empty or not provided")
ValueError: Group variable is empty or not provided
CDDL metrics failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/report.py", line 292, in _categorical_metric_call_wrapper
    group_variable=group_variable,
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/__init__.py", line 26, in call_metric
    return metric(**{key: kwargs[key] for key in inspect.signature(metric).parameters.keys()})
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/pretraining.py", line 195, in CDDL
    return common.CDD(feature, sensitive_facet_index, positive_label_index, group_variable)
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/common.py", line 80, in CDD
    raise ValueError("Group variable is empty or not provided")
ValueError: Group variable is empty or not provided
CDDL metrics failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/report.py", line 292, in _categorical_metric_call_wrapper
    group_variable=group_variable,
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/__init__.py", line 26, in call_metric
    return metric(**{key: kwargs[key] for key in inspect.signature(metric).parameters.keys()})
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/pretraining.py", line 195, in CDDL
    return common.CDD(feature, sensitive_facet_index, positive_label_index, group_variable)
  File "/opt/conda/lib/python3.7/site-packages/smclarify/bias/metrics/common.py", line 80, in CDD
    raise ValueError("Group variable is empty or not provided")
ValueError: Group variable is empty or not provided
``` 

Is this a problem with the example? Could it be caused by the Pandas upgrade? Any help or advice would be much appreciated?

**Comment by milah** [comment]
Hi Oliver-Chalkley,

The CDDL metric requires you to pass in a group_variable in the call to `report.bias_report(df, facet_column, label_column, stage_type=report.StageType.PRE_TRAINING)`. We specify one in the notebook Bias_metrics_usage.ipynb but not in the notebook Bias_metrics_usage_marketing.ipynb. 
Note that the error is just logged, the computation of the other metrics still succeeds. 

You have a few options: (a) ignore the logged error, (b) manually specify a list of metrics excluding CDDL, (c) specifying a group variable.

Here are some details:

(b) you can call `report.bias_report(df, facet_column, label_column, stage_type=report.StageType.PRE_TRAINING, metrics=["CI", "DPL", "JS", "KL", "KS", "LP", "TVD"])` to skip CDDL

(c) you can specify a group_variable of your choice, e.g. `report.bias_report(df, facet_column, label_column, stage_type=report.StageType.PRE_TRAINING, group_variable=df['marital'])`

Hope this helps!
Mila

**Comment by Oliver-Chalkley** [comment]
Great explanation milah, thank you very much!
